services:
  postgres:
    image: postgres:17.0-alpine
    container_name: postgres
    working_dir: /application
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
